# Generated by Django 4.0.2 on 2022-03-06 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userextrafields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtraFields',
        ),
    ]
