# Generated by Django 4.0.2 on 2022-03-15 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_userextrafields_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextrafields',
            name='invitation_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_invitation_code', to='home.invitationcode'),
        ),
    ]
