# Generated by Django 4.0.2 on 2022-03-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_userextrafields_invitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextrafields',
            name='updated_vip',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
