# Generated by Django 4.0.2 on 2022-03-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userextrafields_updated_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextrafields',
            name='updated_vip',
        ),
    ]
