# Generated by Django 4.0.2 on 2022-03-06 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userextrafields_datatoaccept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatoaccept',
            name='vip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.vip'),
        ),
    ]
