# Generated by Django 4.0.2 on 2022-03-17 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_userextrafields_updated_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextrafields',
            name='updated_vip',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
