# Generated by Django 4.0.2 on 2022-03-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_datatoaccept_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatoaccept',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
