# Generated by Django 4.0.2 on 2022-03-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userextrafields_invitation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=255)),
                ('code_verification', models.BigIntegerField()),
            ],
        ),
    ]
