# Generated by Django 4.0.2 on 2022-03-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_userextrafields_updated_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextrafields',
            name='remaining_days_vip',
            field=models.IntegerField(default=0),
        ),
    ]
