# Generated by Django 4.0.2 on 2022-03-17 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_userextrafields_remaining_days_vip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextrafields',
            name='remaining_days_vip',
        ),
        migrations.AlterField(
            model_name='userextrafields',
            name='updated_vip',
            field=models.DateField(default=datetime.date(2022, 3, 17)),
        ),
    ]
