# Generated by Django 4.0.2 on 2022-03-17 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_userextrafields_remaining_days_vip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextrafields',
            name='updated_vip',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
