# Generated by Django 4.0.2 on 2022-03-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_userextrafields_assigned_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='percentage',
            field=models.IntegerField(default=100, null=True),
        ),
    ]
