# Generated by Django 4.0.2 on 2022-03-12 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.BigIntegerField(default=0, null=True)),
                ('total_benefit', models.BigIntegerField(default=0, null=True)),
                ('frozen_quantity', models.BigIntegerField(default=0, null=True)),
                ('day_benefit', models.BigIntegerField(default=0, null=True)),
                ('expiration_time', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
