# Generated by Django 4.0.2 on 2022-03-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
