# Generated by Django 4.0.2 on 2022-03-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_bankaccounts_withdrawalcurrent_withdrawalhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalcurrent',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='center.bankaccounts'),
        ),
    ]
