# Generated by Django 4.0.2 on 2022-03-19 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_alter_withdrawalcurrent_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayBenefitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('points', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.points')),
            ],
        ),
    ]
