# Generated by Django 4.0.2 on 2022-03-19 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_daybenefithistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DayBenefitHistory',
            new_name='PointsHistory',
        ),
    ]
