# Generated by Django 4.0.2 on 2022-03-19 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('center', '0006_rename_daybenefithistory_pointshistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointshistory',
            name='points',
        ),
        migrations.AddField(
            model_name='pointshistory',
            name='points_day',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='pointshistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
