# Generated by Django 4.0.2 on 2022-03-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0007_remove_pointshistory_points_pointshistory_points_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalcurrent',
            name='bank_account',
        ),
        migrations.AddField(
            model_name='withdrawalcurrent',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalcurrent',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalcurrent',
            name='name_bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
