# Generated by Django 4.0.2 on 2022-03-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtasks',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commissions',
            name='unused_withdrawals',
            field=models.IntegerField(default=0),
        ),
    ]
