# Generated by Django 4.0.2 on 2022-03-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskamount_taskhistory_taskamount_task_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissions',
            name='personal_commission',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
