# Generated by Django 4.0.2 on 2022-03-11 04:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_assignedtasks_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtasks',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 4, 39, 17, 502753, tzinfo=utc)),
        ),
    ]
