# Generated by Django 4.0.2 on 2022-03-11 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_assignedtasks_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtasks',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
