# Generated by Django 4.0.2 on 2022-03-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_assignedtasks_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtasks',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
