# Generated by Django 4.0.2 on 2022-03-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_assignedtasks_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissions',
            name='completed_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='personal_commission',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='commissions',
            name='total_assets',
            field=models.BigIntegerField(null=True),
        ),
    ]
