# Generated by Django 4.0.2 on 2022-03-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_commissions_completed_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissions',
            name='total_assets',
        ),
        migrations.RemoveField(
            model_name='commissions',
            name='unused_withdrawals',
        ),
    ]
