# Generated by Django 4.0.2 on 2022-03-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_remove_commissions_total_assets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
